packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  react: ^19.2.3
  react-dom: ^19.2.3
  convex: ^1.31.2
  better-auth: 1.4.9
  "@convex-dev/better-auth": ^0.10.9
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
